# permissions for end users to view nextclouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: nextcloud-viewer-role
rules:
- apiGroups:
  - nc.waveywaves.com
  resources:
  - nextclouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nc.waveywaves.com
  resources:
  - nextclouds/status
  verbs:
  - get
